# -*- coding: utf-8 -*-
"""Counting-islands.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CyNztyrKO-ZEHSltIfM_ux5ZJ_DBRkO-
"""

def count_islands(matrix):
    if not matrix:
        return 0

    rows, cols = len(matrix), len(matrix[0])
    count = 0

    def dfs(i, j):
        if i < 0 or i >= rows or j < 0 or j >= cols or matrix[i][j] == 0:
            return

        matrix[i][j] = 0
        dfs(i+1, j)
        dfs(i-1, j)
        dfs(i, j+1)
        dfs(i, j-1)

    for i in range(rows):
        for j in range(cols):
            if matrix[i][j] == 1:
                count += 1
                dfs(i, j)

    return count

